CREATE TABLE IF NOT EXISTS payment_links (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  reference VARCHAR(50) NOT NULL UNIQUE,
  description VARCHAR(255) DEFAULT NULL,
  amount DECIMAL(10,3) NOT NULL,
  currency VARCHAR(3) NOT NULL DEFAULT 'KWD',
  status ENUM('pending','paid','expired','cancelled') NOT NULL DEFAULT 'pending',
  order_id INT UNSIGNED DEFAULT NULL,
  gateway_link_id VARCHAR(100) DEFAULT NULL,
  expires_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
